<a href="https://colab.research.google.com/github/oartuu/DATAMINING/blob/main/DATAMINING.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#**DATA MINING**

##CARREGANDO OS DATASETS

In [1]:
import pandas as pd

In [8]:
import glob
import pandas as pd

# ==========================
# CARREGAR INFRAÇÕES
# ==========================

arquivos_infra = glob.glob('/content/datasets/infracoes/*.csv')

dfs_infra = [
    pd.read_csv(
        arq,
        sep=';',
        encoding='latin1'
    )
    for arq in arquivos_infra
]

infra = pd.concat(
    dfs_infra,
    ignore_index=True
)

# ==========================
# CARREGAR ACIDENTES
# ==========================

arquivos_acidentes = glob.glob('/content/datasets/acidentes/*.csv')

dfs_acidentes = [
    pd.read_csv(
        arq,
        sep=';',
        encoding='latin1'
    )
    for arq in arquivos_acidentes
]

acidentes = pd.concat(
    dfs_acidentes,
    ignore_index=True
)

# ==========================
# VERIFICAÇÃO
# ==========================

print("INFRAÇÕES")
print(infra.shape)

print("\nACIDENTES")
print(acidentes.shape)

print("\nPrimeiras linhas de infrações")
display(infra.head())

print("\nPrimeiras linhas de acidentes")
display(acidentes.head())

/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(
/tmp/ipykernel_12372/3790894843.py:11: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  pd.read_csv(

INFRAÇÕES
(5241299, 22)

ACIDENTES
(166287, 35)

Primeiras linhas de infrações

,Número do Auto,Data da Infração (DD/MM/AAAA),Indicador de Abordagem,Assinatura do Auto,Indicador Veiculo Estrangeiro,Sentido Trafego,UF Infração,BR Infração,Km Infração,Município,...,Enquadramento da Infração,Início Vigência da Infração,Fim Vigência Infração,Medição Infração,Descrição Especie Veículo,Descrição Marca Veículo,Hora Infração,Medição Considerada,Excesso Verificado,Qtd Infrações
0,30ce2531bbb07db,2021-05-13,C,N,N,D,RJ,116,184,NOVA IGUACU,...,230 * V,2016-11-01,NaN,Nenhuma,CARGA,VW,15,0,0,1
1,7bbe678946b0ef9,2021-05-13,C,N,N,D,RJ,116,184,NOVA IGUACU,...,231 V,2016-11-01,NaN,Peso,CARGA,VW,15,37070,12920,1
2,4d281c6ebf4f08e,2021-05-28,C,N,N,D,PR,369,451,UBIRATA,...,162 V,2016-11-01,NaN,Nenhuma,PASSAGEIRO,RENAULT,20,0,0,1
3,978040794af098e,2021-05-28,C,N,N,D,PR,369,451,UBIRATA,...,182-V,2016-11-01,NaN,Nenhuma,PASSAGEIRO,RENAULT,20,0,0,1
4,e24a9ac8bea2cc4,2021-05-12,C,N,N,C,MA,230,402,BALSAS,...,230 * V,2016-11-01,NaN,Nenhuma,CARGA,OUTRA,10,0,0,1

Primeiras linhas de acidentes

,id,pesid,data_inversa,dia_semana,horario,uf,br,km,municipio,causa_acidente,...,sexo,ilesos,feridos_leves,feridos_graves,mortos,latitude,longitude,regional,delegacia,uop
0,331730.0,738258,2021-01-01,sexta-feira,05:30:00,SP,116,453,REGISTRO,Reação tardia ou ineficiente do condutor,...,Masculino,0,1,0,0,"-24,56168114","-47,86752174",SPRF-SP,DEL05-SP,UOP01-DEL05-SP
1,331804.0,738412,2021-01-01,sexta-feira,08:05:00,AM,174,937,MANAUS,Reação tardia ou ineficiente do condutor,...,Masculino,1,0,0,0,"-2,508068","-60,036434",SPRF-AM,DEL01-AM,UOP01-DEL01-AM
2,331815.0,738689,2021-01-01,sexta-feira,10:10:00,CE,222,"128,5",ITAPAJE,Velocidade Incompatível,...,Masculino,0,1,0,0,"-3,707626","-39,623509",SPRF-CE,DEL04-CE,UOP03-DEL04-CE
3,331815.0,738692,2021-01-01,sexta-feira,10:10:00,CE,222,"128,5",ITAPAJE,Velocidade Incompatível,...,Feminino,0,1,0,0,"-3,707626","-39,623509",SPRF-CE,DEL04-CE,UOP03-DEL04-CE
4,331823.0,740272,2021-01-01,sexta-feira,12:30:00,RJ,493,18,MAGE,Ingestão de álcool e/ou substâncias psicoativa...,...,Masculino,1,0,0,0,"-22,6687122","-43,01862696",SPRF-RJ,DEL04-RJ,UOP02-DEL04-RJ

##VISUALIZANDO COLUNAS E TIPOS

In [9]:
print("COLUNAS INFRAÇÕES")
print(infra.columns.tolist())

print("\nCOLUNAS ACIDENTES")
print(acidentes.columns.tolist())

COLUNAS INFRAÇÕES
['Número do Auto', 'Data da Infração (DD/MM/AAAA)', 'Indicador de Abordagem', 'Assinatura do Auto', 'Indicador Veiculo Estrangeiro', 'Sentido Trafego', 'UF Infração', 'BR Infração', 'Km Infração', 'Município', 'Código da Infração', 'Descrição Abreviada Infração', 'Enquadramento da Infração', 'Início Vigência da Infração', 'Fim Vigência Infração', 'Medição Infração', 'Descrição Especie Veículo', 'Descrição Marca Veículo', 'Hora Infração', 'Medição Considerada', 'Excesso Verificado', 'Qtd Infrações']

COLUNAS ACIDENTES
['id', 'pesid', 'data_inversa', 'dia_semana', 'horario', 'uf', 'br', 'km', 'municipio', 'causa_acidente', 'tipo_acidente', 'classificacao_acidente', 'fase_dia', 'sentido_via', 'condicao_metereologica', 'tipo_pista', 'tracado_via', 'uso_solo', 'id_veiculo', 'tipo_veiculo', 'marca', 'ano_fabricacao_veiculo', 'tipo_envolvido', 'estado_fisico', 'idade', 'sexo', 'ilesos', 'feridos_leves', 'feridos_graves', 'mortos', 'latitude', 'longitude', 'regional', 'delegacia', 'uop']

In [10]:
infra.info()

print("\n" + "="*50 + "\n")

acidentes.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5241299 entries, 0 to 5241298
Data columns (total 22 columns):
 #   Column                         Dtype
---  ------                         -----
 0   Número do Auto                 object
 1   Data da Infração (DD/MM/AAAA)  object
 2   Indicador de Abordagem         object
 3   Assinatura do Auto             object
 4   Indicador Veiculo Estrangeiro  object
 5   Sentido Trafego                object
 6   UF Infração                    object
 7   BR Infração                    int64
 8   Km Infração                    int64
 9   Município                      object
 10  Código da Infração             int64
 11  Descrição Abreviada Infração   object
 12  Enquadramento da Infração      object
 13  Início Vigência da Infração    object
 14  Fim Vigência Infração          float64
 15  Medição Infração               object
 16  Descrição Especie Veículo      object
 17  Descrição Marca Veículo        object
 18  Hora Infração                  int64
 19  Medição Considerada            object
 20  Excesso Verificado             object
 21  Qtd Infrações                  int64
dtypes: float64(1), int64(5), object(16)
memory usage: 879.7+ MB

==================================================

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 166287 entries, 0 to 166286
Data columns (total 35 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   id                      166287 non-null  float64
 1   pesid                   166287 non-null  int64
 2   data_inversa            166287 non-null  object
 3   dia_semana              166287 non-null  object
 4   horario                 166287 non-null  object
 5   uf                      166287 non-null  object
 6   br                      166287 non-null  int64
 7   km                      166287 non-null  object
 8   municipio               166287 non-null  object
 9   causa_acidente          166287 non-null  object
 10  tipo_acidente           166287 non-null  object
 11  classificacao_acidente  166280 non-null  object
 12  fase_dia                166287 non-null  object
 13  sentido_via             166287 non-null  object
 14  condicao_metereologica  166287 non-null  object
 15  tipo_pista              166287 non-null  object
 16  tracado_via             166287 non-null  object
 17  uso_solo                166287 non-null  object
 18  id_veiculo              166287 non-null  int64
 19  tipo_veiculo            160033 non-null  object
 20  marca                   166287 non-null  object
 21  ano_fabricacao_veiculo  166287 non-null  int64
 22  tipo_envolvido          150974 non-null  object
 23  estado_fisico           150974 non-null  object
 24  idade                   166287 non-null  int64
 25  sexo                    150974 non-null  object
 26  ilesos                  166287 non-null  int64
 27  feridos_leves           166287 non-null  int64
 28  feridos_graves          166287 non-null  int64
 29  mortos                  166287 non-null  int64
 30  latitude                166287 non-null  object
 31  longitude               166287 non-null  object
 32  regional                166287 non-null  object
 33  delegacia               166230 non-null  object
 34  uop                     166184 non-null  object
dtypes: float64(1), int64(9), object(25)
memory usage: 44.4+ MB

##UNIFICANDO DATASETS DE INFRAÇÕES

In [15]:
dfs_infra = []

for arquivo in arquivos_infra:

    df = pd.read_csv(
        arquivo,
        sep=';',
        encoding='latin1'
    )

    dfs_infra.append(df)

/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(
/tmp/ipykernel_12372/3695792289.py:5: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(

In [16]:
print(len(dfs_infra))

12

In [17]:
infra = pd.concat(
    dfs_infra,
    ignore_index=True
)

In [48]:
print(infra.columns.tolist())

['Número do Auto', 'Data da Infração (DD/MM/AAAA)', 'Indicador de Abordagem', 'Assinatura do Auto', 'Indicador Veiculo Estrangeiro', 'Sentido Trafego', 'UF Infração', 'BR Infração', 'Km Infração', 'Município', 'Código da Infração', 'Descrição Abreviada Infração', 'Enquadramento da Infração', 'Início Vigência da Infração', 'Fim Vigência Infração', 'Medição Infração', 'Descrição Especie Veículo', 'Descrição Marca Veículo', 'Hora Infração', 'Medição Considerada', 'Excesso Verificado', 'Qtd Infrações']

###SALVA DATASET UNIFICADO

In [49]:
infra.to_csv(
    '/content/infra_unificado.csv',
    index=False
)

##ETL

###DIAGNÓSTICO GERAL

In [52]:
infra_unificado = pd.read_csv(
    '/content/infra_unificado.csv'
)

/tmp/ipykernel_12372/114831294.py:1: DtypeWarning: Columns (19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  infra_unificado = pd.read_csv(

In [53]:
infra_unificado.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5241299 entries, 0 to 5241298
Data columns (total 22 columns):
 #   Column                         Dtype
---  ------                         -----
 0   Número do Auto                 object
 1   Data da Infração (DD/MM/AAAA)  object
 2   Indicador de Abordagem         object
 3   Assinatura do Auto             object
 4   Indicador Veiculo Estrangeiro  object
 5   Sentido Trafego                object
 6   UF Infração                    object
 7   BR Infração                    int64
 8   Km Infração                    int64
 9   Município                      object
 10  Código da Infração             int64
 11  Descrição Abreviada Infração   object
 12  Enquadramento da Infração      object
 13  Início Vigência da Infração    object
 14  Fim Vigência Infração          float64
 15  Medição Infração               object
 16  Descrição Especie Veículo      object
 17  Descrição Marca Veículo        object
 18  Hora Infração                  int64
 19  Medição Considerada            object
 20  Excesso Verificado             object
 21  Qtd Infrações                  int64
dtypes: float64(1), int64(5), object(16)
memory usage: 879.7+ MB

In [54]:
infra_unificado.isnull().sum().sort_values(ascending=False)

Fim Vigência Infração            5241299
Indicador Veiculo Estrangeiro        744
Descrição Especie Veículo            744
Descrição Marca Veículo              744
Data da Infração (DD/MM/AAAA)          0
Número do Auto                         0
Sentido Trafego                        0
Assinatura do Auto                     0
Indicador de Abordagem                 0
UF Infração                            0
Código da Infração                     0
BR Infração                            0
Km Infração                            0
Município                              0
Início Vigência da Infração            0
Enquadramento da Infração              0
Descrição Abreviada Infração           0
Medição Infração                       0
Hora Infração                          0
Medição Considerada                    0
Excesso Verificado                     0
Qtd Infrações                          0
dtype: int64

In [61]:
infra_unificado['Descrição Marca Veículo'].value_counts(dropna=False).head(20)

Descrição Marca Veículo
'-1                       2154976
HONDA                      441336
VW                         428454
OUTRA                      345847
FIAT                       294569
GM                         269493
MERCEDES BENZ              210752
FORD                       191031
VOLVO                       99279
SCANIA                      93709
TOYOTA                      90179
RENAULT                     60973
YAMAHA                      60394
PEUGEOT                     19562
KIA                          6917
COROLLA GLI UPPER            5604
COROLLA XEI20FLEX            4292
TOYOTA HILUX CD4X4 SRV       2836
TOYOTA HILUX SWSRXA4FD       2571
TOYOTA HILUX CDSRXA4FD       2473
Name: count, dtype: int64

In [62]:
infra_unificado['Descrição Especie Veículo'].value_counts(dropna=False).head(20)

Descrição Especie Veículo
'-1           2200340
PASSAGEIRO    1738739
CARGA          663565
TRAÇÃO         276806
ESPECIAL       201215
MISTO          159662
NaN               744
COMPETIÇÃO        114
COLEÇÃO           114
Name: count, dtype: int64

##REMOVER VALORES INVÁLIDOS ENCONTRADOS

In [63]:
import numpy as np

infra_unificado['Descrição Marca Veículo'] = (
    infra['Descrição Marca Veículo']
    .replace("'-1", np.nan)
)

infra_unificado['Descrição Especie Veículo'] = (
    infra['Descrição Especie Veículo']
    .replace("'-1", np.nan)
)

In [64]:
infra_unificado[
    [
        'Descrição Marca Veículo',
        'Descrição Especie Veículo'
    ]
].isnull().sum()

Descrição Marca Veículo      2155720
Descrição Especie Veículo    2201084
dtype: int64